### ISSUE TITLE
BUG-1: Cannot read property 'liked_by' of null

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN341-UA2#87]
* A bug has been merged to develop 
* Can be first identified here: https://travis-ci.com/RGPosadas/SOEN341-UA2/builds/105017874
* Bug was triggered by #76, from PR #84  

Acceptance criteria:
* Error no longer appears when a successful test of like occurs

```
Tweet successfully found in database
Query results: null
events.js:173
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'liked_by' of null
    at /home/travis/build/RGPosadas/SOEN341-UA2/src/UserDatabase/test/test.js:139:19
    at /home/travis/build/RGPosadas/SOEN341-UA2/src/UserDatabase/node_modules/mongoose/lib/model.js:4687:16
    at /home/travis/build/RGPosadas/SOEN341-UA2/src/UserDatabase/node_modules/mongoose/lib/query.js:4095:12
    at model.Query.Query._completeOne (/home/travis/build/RGPosadas/SOEN341-UA2/src/UserDatabase/node_modules/mongoose/lib/query.js:1934:12)
    at Immediate.Query.base.findOne.call (/home/travis/build/RGPosadas/SOEN341-UA2/src/UserDatabase/node_modules/mongoose/lib/query.js:1994:10)
    at Immediate.<anonymous> (/home/travis/build/RGPosadas/SOEN341-UA2/src/UserDatabase/node_modules/mquery/lib/utils.js:116:16)
    at processImmediate (timers.js:638:19)
Emitted 'error' event at:
    at /home/travis/build/RGPosadas/SOEN341-UA2/src/UserDatabase/node_modules/mongoose/lib/model.js:4689:13
    at /home/travis/build/RGPosadas/SOEN341-UA2/src/UserDatabase/node_modules/mongoose/lib/query.js:4095:12
    [... lines matching original stack trace ...]
    at processImmediate (timers.js:638:19)
```

**Comment by RGPosadas** [comment]
Closed since #89 has been merged
